package com.fuchuan.nsc.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("account", "id", Account.class);
		arp.addMapping("comment", "id", Comment.class);
		arp.addMapping("follow", "id", Follow.class);
		arp.addMapping("message", "id", Message.class);
		arp.addMapping("newsfeed", "id", Newsfeed.class);
		arp.addMapping("post", "id", Post.class);
		// Composite Primary Key order: accountId,postId
		arp.addMapping("post_like", "accountId,postId", PostLike.class);
		// Composite Primary Key order: accountId,postId
		arp.addMapping("post_nay", "accountId,postId", PostNay.class);
		arp.addMapping("remind", "accountId", Remind.class);
		arp.addMapping("session", "id", Session.class);
	}
}

