package com.fuchuan.nsc.common.model;

import com.fuchuan.nsc.common.model.base.BaseAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Account extends BaseAccount<Account> {
	
}
