package com.fuchuan.nsc.common.model;

import com.fuchuan.nsc.common.model.base.BaseAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Account extends BaseAccount<Account> {
	public static final Account dao = new Account().dao();

	public String getSomething(){
		return getStr("something"); 
	}

	public void setSomething(String something){
		set("something", something); 
	}
}
