package com.fuchuan.nsc.common.model;

import com.fuchuan.nsc.common.model.base.BaseFollow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Follow extends BaseFollow<Follow> {
	
}
