package com.fuchuan.nsc.common.model;

import com.fuchuan.nsc.common.model.base.BaseNewsfeed;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Newsfeed extends BaseNewsfeed<Newsfeed> {
	public static final Newsfeed dao = new Newsfeed().dao();
}
