package com.fuchuan.nsc.common.model;

import com.fuchuan.nsc.common.model.base.BasePostNay;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PostNay extends BasePostNay<PostNay> {
	
}
