package com.fuchuan.nsc.common.model;

import com.fuchuan.nsc.common.model.base.BasePostLike;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PostLike extends BasePostLike<PostLike> {
	
}
