package com.fuchuan.nsc.common.model;

import com.fuchuan.nsc.common.model.base.BasePost;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Post extends BasePost<Post> {
	public static final Post dao = new Post().dao();
}
