package com.fuchuan.nsc.common.model;

import com.fuchuan.nsc.common.model.base.BaseRemind;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Remind extends BaseRemind<Remind> {
	public static final Remind dao = new Remind().dao();
}
