package com.fuchuan.nsc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePostNay<M extends BasePostNay<M>> extends Model<M> implements IBean {

	public void setAccountId(java.lang.Long accountId) {
		set("accountId", accountId);
	}
	
	public java.lang.Long getAccountId() {
		return getLong("accountId");
	}

	public void setPostId(java.lang.Long postId) {
		set("postId", postId);
	}
	
	public java.lang.Long getPostId() {
		return getLong("postId");
	}

	public void setCreateAt(java.lang.Integer createAt) {
		set("createAt", createAt);
	}
	
	public java.lang.Integer getCreateAt() {
		return getInt("createAt");
	}

}
