package com.fuchuan.nsc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePost<M extends BasePost<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setCreateAt(java.lang.Long createAt) {
		set("createAt", createAt);
	}
	
	public java.lang.Long getCreateAt() {
		return getLong("createAt");
	}

	public void setLikeCount(java.lang.Integer likeCount) {
		set("likeCount", likeCount);
	}
	
	public java.lang.Integer getLikeCount() {
		return getInt("likeCount");
	}

	public void setNayCount(java.lang.Integer nayCount) {
		set("nayCount", nayCount);
	}
	
	public java.lang.Integer getNayCount() {
		return getInt("nayCount");
	}

	public void setModifyAt(java.lang.Long modifyAt) {
		set("modifyAt", modifyAt);
	}
	
	public java.lang.Long getModifyAt() {
		return getLong("modifyAt");
	}

	public void setAccountId(java.lang.Integer accountId) {
		set("accountId", accountId);
	}
	
	public java.lang.Integer getAccountId() {
		return getInt("accountId");
	}

}
