package com.fuchuan.nsc.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseFollow<M extends BaseFollow<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setFromId(java.lang.Integer fromId) {
		set("fromId", fromId);
	}
	
	public java.lang.Integer getFromId() {
		return getInt("fromId");
	}

	public void setToId(java.lang.Integer toId) {
		set("toId", toId);
	}
	
	public java.lang.Integer getToId() {
		return getInt("toId");
	}

	public void setCreateAt(java.lang.Long createAt) {
		set("createAt", createAt);
	}
	
	public java.lang.Long getCreateAt() {
		return getLong("createAt");
	}

}
